// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RelatedInfoObj.proto

package com.dtc.analytic.online.protobuf;

public final class RelatedInfoObjProto {
  private RelatedInfoObjProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RelatedInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.dtc.analytic.online.protobuf.RelatedInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *关联类型
     * </pre>
     *
     * <code>string relatedType = 1;</code>
     * @return The relatedType.
     */
    java.lang.String getRelatedType();
    /**
     * <pre>
     *关联类型
     * </pre>
     *
     * <code>string relatedType = 1;</code>
     * @return The bytes for relatedType.
     */
    com.google.protobuf.ByteString
        getRelatedTypeBytes();

    /**
     * <pre>
     *数据关联id
     * </pre>
     *
     * <code>string relatedId = 2;</code>
     * @return The relatedId.
     */
    java.lang.String getRelatedId();
    /**
     * <pre>
     *数据关联id
     * </pre>
     *
     * <code>string relatedId = 2;</code>
     * @return The bytes for relatedId.
     */
    com.google.protobuf.ByteString
        getRelatedIdBytes();

    /**
     * <pre>
     *网力企标关联关系ID
     * </pre>
     *
     * <code>string relatedNPId = 3;</code>
     * @return The relatedNPId.
     */
    java.lang.String getRelatedNPId();
    /**
     * <pre>
     *网力企标关联关系ID
     * </pre>
     *
     * <code>string relatedNPId = 3;</code>
     * @return The bytes for relatedNPId.
     */
    com.google.protobuf.ByteString
        getRelatedNPIdBytes();
  }
  /**
   * Protobuf type {@code com.dtc.analytic.online.protobuf.RelatedInfo}
   */
  public  static final class RelatedInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.dtc.analytic.online.protobuf.RelatedInfo)
      RelatedInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RelatedInfo.newBuilder() to construct.
    private RelatedInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RelatedInfo() {
      relatedType_ = "";
      relatedId_ = "";
      relatedNPId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RelatedInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RelatedInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              relatedType_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              relatedId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              relatedNPId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dtc.analytic.online.protobuf.RelatedInfoObjProto.internal_static_com_dtc_analytic_online_protobuf_RelatedInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dtc.analytic.online.protobuf.RelatedInfoObjProto.internal_static_com_dtc_analytic_online_protobuf_RelatedInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo.class, com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo.Builder.class);
    }

    public static final int RELATEDTYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object relatedType_;
    /**
     * <pre>
     *关联类型
     * </pre>
     *
     * <code>string relatedType = 1;</code>
     * @return The relatedType.
     */
    public java.lang.String getRelatedType() {
      java.lang.Object ref = relatedType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        relatedType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *关联类型
     * </pre>
     *
     * <code>string relatedType = 1;</code>
     * @return The bytes for relatedType.
     */
    public com.google.protobuf.ByteString
        getRelatedTypeBytes() {
      java.lang.Object ref = relatedType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        relatedType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RELATEDID_FIELD_NUMBER = 2;
    private volatile java.lang.Object relatedId_;
    /**
     * <pre>
     *数据关联id
     * </pre>
     *
     * <code>string relatedId = 2;</code>
     * @return The relatedId.
     */
    public java.lang.String getRelatedId() {
      java.lang.Object ref = relatedId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        relatedId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *数据关联id
     * </pre>
     *
     * <code>string relatedId = 2;</code>
     * @return The bytes for relatedId.
     */
    public com.google.protobuf.ByteString
        getRelatedIdBytes() {
      java.lang.Object ref = relatedId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        relatedId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RELATEDNPID_FIELD_NUMBER = 3;
    private volatile java.lang.Object relatedNPId_;
    /**
     * <pre>
     *网力企标关联关系ID
     * </pre>
     *
     * <code>string relatedNPId = 3;</code>
     * @return The relatedNPId.
     */
    public java.lang.String getRelatedNPId() {
      java.lang.Object ref = relatedNPId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        relatedNPId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *网力企标关联关系ID
     * </pre>
     *
     * <code>string relatedNPId = 3;</code>
     * @return The bytes for relatedNPId.
     */
    public com.google.protobuf.ByteString
        getRelatedNPIdBytes() {
      java.lang.Object ref = relatedNPId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        relatedNPId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRelatedTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, relatedType_);
      }
      if (!getRelatedIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, relatedId_);
      }
      if (!getRelatedNPIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, relatedNPId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRelatedTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, relatedType_);
      }
      if (!getRelatedIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, relatedId_);
      }
      if (!getRelatedNPIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, relatedNPId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo)) {
        return super.equals(obj);
      }
      com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo other = (com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo) obj;

      if (!getRelatedType()
          .equals(other.getRelatedType())) return false;
      if (!getRelatedId()
          .equals(other.getRelatedId())) return false;
      if (!getRelatedNPId()
          .equals(other.getRelatedNPId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RELATEDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getRelatedType().hashCode();
      hash = (37 * hash) + RELATEDID_FIELD_NUMBER;
      hash = (53 * hash) + getRelatedId().hashCode();
      hash = (37 * hash) + RELATEDNPID_FIELD_NUMBER;
      hash = (53 * hash) + getRelatedNPId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.dtc.analytic.online.protobuf.RelatedInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.dtc.analytic.online.protobuf.RelatedInfo)
        com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dtc.analytic.online.protobuf.RelatedInfoObjProto.internal_static_com_dtc_analytic_online_protobuf_RelatedInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dtc.analytic.online.protobuf.RelatedInfoObjProto.internal_static_com_dtc_analytic_online_protobuf_RelatedInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo.class, com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo.Builder.class);
      }

      // Construct using com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        relatedType_ = "";

        relatedId_ = "";

        relatedNPId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dtc.analytic.online.protobuf.RelatedInfoObjProto.internal_static_com_dtc_analytic_online_protobuf_RelatedInfo_descriptor;
      }

      @java.lang.Override
      public com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo getDefaultInstanceForType() {
        return com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo build() {
        com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo buildPartial() {
        com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo result = new com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo(this);
        result.relatedType_ = relatedType_;
        result.relatedId_ = relatedId_;
        result.relatedNPId_ = relatedNPId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo) {
          return mergeFrom((com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo other) {
        if (other == com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo.getDefaultInstance()) return this;
        if (!other.getRelatedType().isEmpty()) {
          relatedType_ = other.relatedType_;
          onChanged();
        }
        if (!other.getRelatedId().isEmpty()) {
          relatedId_ = other.relatedId_;
          onChanged();
        }
        if (!other.getRelatedNPId().isEmpty()) {
          relatedNPId_ = other.relatedNPId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object relatedType_ = "";
      /**
       * <pre>
       *关联类型
       * </pre>
       *
       * <code>string relatedType = 1;</code>
       * @return The relatedType.
       */
      public java.lang.String getRelatedType() {
        java.lang.Object ref = relatedType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          relatedType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *关联类型
       * </pre>
       *
       * <code>string relatedType = 1;</code>
       * @return The bytes for relatedType.
       */
      public com.google.protobuf.ByteString
          getRelatedTypeBytes() {
        java.lang.Object ref = relatedType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          relatedType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *关联类型
       * </pre>
       *
       * <code>string relatedType = 1;</code>
       * @param value The relatedType to set.
       * @return This builder for chaining.
       */
      public Builder setRelatedType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        relatedType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *关联类型
       * </pre>
       *
       * <code>string relatedType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRelatedType() {
        
        relatedType_ = getDefaultInstance().getRelatedType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *关联类型
       * </pre>
       *
       * <code>string relatedType = 1;</code>
       * @param value The bytes for relatedType to set.
       * @return This builder for chaining.
       */
      public Builder setRelatedTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        relatedType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object relatedId_ = "";
      /**
       * <pre>
       *数据关联id
       * </pre>
       *
       * <code>string relatedId = 2;</code>
       * @return The relatedId.
       */
      public java.lang.String getRelatedId() {
        java.lang.Object ref = relatedId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          relatedId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *数据关联id
       * </pre>
       *
       * <code>string relatedId = 2;</code>
       * @return The bytes for relatedId.
       */
      public com.google.protobuf.ByteString
          getRelatedIdBytes() {
        java.lang.Object ref = relatedId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          relatedId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *数据关联id
       * </pre>
       *
       * <code>string relatedId = 2;</code>
       * @param value The relatedId to set.
       * @return This builder for chaining.
       */
      public Builder setRelatedId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        relatedId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *数据关联id
       * </pre>
       *
       * <code>string relatedId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRelatedId() {
        
        relatedId_ = getDefaultInstance().getRelatedId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *数据关联id
       * </pre>
       *
       * <code>string relatedId = 2;</code>
       * @param value The bytes for relatedId to set.
       * @return This builder for chaining.
       */
      public Builder setRelatedIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        relatedId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object relatedNPId_ = "";
      /**
       * <pre>
       *网力企标关联关系ID
       * </pre>
       *
       * <code>string relatedNPId = 3;</code>
       * @return The relatedNPId.
       */
      public java.lang.String getRelatedNPId() {
        java.lang.Object ref = relatedNPId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          relatedNPId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *网力企标关联关系ID
       * </pre>
       *
       * <code>string relatedNPId = 3;</code>
       * @return The bytes for relatedNPId.
       */
      public com.google.protobuf.ByteString
          getRelatedNPIdBytes() {
        java.lang.Object ref = relatedNPId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          relatedNPId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *网力企标关联关系ID
       * </pre>
       *
       * <code>string relatedNPId = 3;</code>
       * @param value The relatedNPId to set.
       * @return This builder for chaining.
       */
      public Builder setRelatedNPId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        relatedNPId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *网力企标关联关系ID
       * </pre>
       *
       * <code>string relatedNPId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRelatedNPId() {
        
        relatedNPId_ = getDefaultInstance().getRelatedNPId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *网力企标关联关系ID
       * </pre>
       *
       * <code>string relatedNPId = 3;</code>
       * @param value The bytes for relatedNPId to set.
       * @return This builder for chaining.
       */
      public Builder setRelatedNPIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        relatedNPId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.dtc.analytic.online.protobuf.RelatedInfo)
    }

    // @@protoc_insertion_point(class_scope:com.dtc.analytic.online.protobuf.RelatedInfo)
    private static final com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo();
    }

    public static com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RelatedInfo>
        PARSER = new com.google.protobuf.AbstractParser<RelatedInfo>() {
      @java.lang.Override
      public RelatedInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RelatedInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RelatedInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RelatedInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dtc.analytic.online.protobuf.RelatedInfoObjProto.RelatedInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dtc_analytic_online_protobuf_RelatedInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dtc_analytic_online_protobuf_RelatedInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024RelatedInfoObj.proto\022 com.dtc.analytic" +
      ".online.protobuf\"J\n\013RelatedInfo\022\023\n\013relat" +
      "edType\030\001 \001(\t\022\021\n\trelatedId\030\002 \001(\t\022\023\n\013relat" +
      "edNPId\030\003 \001(\tB\025B\023RelatedInfoObjProtob\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_dtc_analytic_online_protobuf_RelatedInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_dtc_analytic_online_protobuf_RelatedInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dtc_analytic_online_protobuf_RelatedInfo_descriptor,
        new java.lang.String[] { "RelatedType", "RelatedId", "RelatedNPId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
