// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SubImageInfoObj.proto

package com.dtc.analytic.online.protobuf;

public final class SubImageInfoObjProto {
  private SubImageInfoObjProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SubImageInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.dtc.analytic.online.protobuf.SubImageInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *设备编码
     * </pre>
     *
     * <code>string deviceId = 1;</code>
     * @return The deviceId.
     */
    java.lang.String getDeviceId();
    /**
     * <pre>
     *设备编码
     * </pre>
     *
     * <code>string deviceId = 1;</code>
     * @return The bytes for deviceId.
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <pre>
     *图像标识
     * </pre>
     *
     * <code>string imageId = 2;</code>
     * @return The imageId.
     */
    java.lang.String getImageId();
    /**
     * <pre>
     *图像标识
     * </pre>
     *
     * <code>string imageId = 2;</code>
     * @return The bytes for imageId.
     */
    com.google.protobuf.ByteString
        getImageIdBytes();

    /**
     * <pre>
     *图像来源
     * </pre>
     *
     * <code>string imageSource = 3;</code>
     * @return The imageSource.
     */
    java.lang.String getImageSource();
    /**
     * <pre>
     *图像来源
     * </pre>
     *
     * <code>string imageSource = 3;</code>
     * @return The bytes for imageSource.
     */
    com.google.protobuf.ByteString
        getImageSourceBytes();

    /**
     * <pre>
     *题名
     * </pre>
     *
     * <code>string title = 4;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <pre>
     *题名
     * </pre>
     *
     * <code>string title = 4;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <pre>
     *图片数据
     * </pre>
     *
     * <code>bytes imageData = 5;</code>
     * @return The imageData.
     */
    com.google.protobuf.ByteString getImageData();

    /**
     * <pre>
     *图像文件格式
     * </pre>
     *
     * <code>string fileFormat = 6;</code>
     * @return The fileFormat.
     */
    java.lang.String getFileFormat();
    /**
     * <pre>
     *图像文件格式
     * </pre>
     *
     * <code>string fileFormat = 6;</code>
     * @return The bytes for fileFormat.
     */
    com.google.protobuf.ByteString
        getFileFormatBytes();

    /**
     * <pre>
     *拍摄地点区划内详细地址
     * </pre>
     *
     * <code>string shotPlaceFullAdress = 7;</code>
     * @return The shotPlaceFullAdress.
     */
    java.lang.String getShotPlaceFullAdress();
    /**
     * <pre>
     *拍摄地点区划内详细地址
     * </pre>
     *
     * <code>string shotPlaceFullAdress = 7;</code>
     * @return The bytes for shotPlaceFullAdress.
     */
    com.google.protobuf.ByteString
        getShotPlaceFullAdressBytes();

    /**
     * <pre>
     *拍摄时间
     * </pre>
     *
     * <code>int64 shotTime = 8;</code>
     * @return The shotTime.
     */
    long getShotTime();

    /**
     * <pre>
     *事件分类
     * </pre>
     *
     * <code>int32 eventSort = 9;</code>
     * @return The eventSort.
     */
    int getEventSort();

    /**
     * <pre>
     *图像类型
     * </pre>
     *
     * <code>int32 imageType = 10;</code>
     * @return The imageType.
     */
    int getImageType();

    /**
     * <pre>
     *信息分类
     * </pre>
     *
     * <code>int32 infoKind = 11;</code>
     * @return The infoKind.
     */
    int getInfoKind();

    /**
     * <pre>
     *存储路径
     * </pre>
     *
     * <code>string storagePath = 12;</code>
     * @return The storagePath.
     */
    java.lang.String getStoragePath();
    /**
     * <pre>
     *存储路径
     * </pre>
     *
     * <code>string storagePath = 12;</code>
     * @return The bytes for storagePath.
     */
    com.google.protobuf.ByteString
        getStoragePathBytes();

    /**
     * <pre>
     *内容描述
     * </pre>
     *
     * <code>string contentDescription = 13;</code>
     * @return The contentDescription.
     */
    java.lang.String getContentDescription();
    /**
     * <pre>
     *内容描述
     * </pre>
     *
     * <code>string contentDescription = 13;</code>
     * @return The bytes for contentDescription.
     */
    com.google.protobuf.ByteString
        getContentDescriptionBytes();
  }
  /**
   * Protobuf type {@code com.dtc.analytic.online.protobuf.SubImageInfo}
   */
  public  static final class SubImageInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.dtc.analytic.online.protobuf.SubImageInfo)
      SubImageInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SubImageInfo.newBuilder() to construct.
    private SubImageInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SubImageInfo() {
      deviceId_ = "";
      imageId_ = "";
      imageSource_ = "";
      title_ = "";
      imageData_ = com.google.protobuf.ByteString.EMPTY;
      fileFormat_ = "";
      shotPlaceFullAdress_ = "";
      storagePath_ = "";
      contentDescription_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SubImageInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SubImageInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              imageId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              imageSource_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 42: {

              imageData_ = input.readBytes();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              fileFormat_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              shotPlaceFullAdress_ = s;
              break;
            }
            case 64: {

              shotTime_ = input.readInt64();
              break;
            }
            case 72: {

              eventSort_ = input.readInt32();
              break;
            }
            case 80: {

              imageType_ = input.readInt32();
              break;
            }
            case 88: {

              infoKind_ = input.readInt32();
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              storagePath_ = s;
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              contentDescription_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dtc.analytic.online.protobuf.SubImageInfoObjProto.internal_static_com_dtc_analytic_online_protobuf_SubImageInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dtc.analytic.online.protobuf.SubImageInfoObjProto.internal_static_com_dtc_analytic_online_protobuf_SubImageInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo.class, com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo.Builder.class);
    }

    public static final int DEVICEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object deviceId_;
    /**
     * <pre>
     *设备编码
     * </pre>
     *
     * <code>string deviceId = 1;</code>
     * @return The deviceId.
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *设备编码
     * </pre>
     *
     * <code>string deviceId = 1;</code>
     * @return The bytes for deviceId.
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGEID_FIELD_NUMBER = 2;
    private volatile java.lang.Object imageId_;
    /**
     * <pre>
     *图像标识
     * </pre>
     *
     * <code>string imageId = 2;</code>
     * @return The imageId.
     */
    public java.lang.String getImageId() {
      java.lang.Object ref = imageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imageId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *图像标识
     * </pre>
     *
     * <code>string imageId = 2;</code>
     * @return The bytes for imageId.
     */
    public com.google.protobuf.ByteString
        getImageIdBytes() {
      java.lang.Object ref = imageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGESOURCE_FIELD_NUMBER = 3;
    private volatile java.lang.Object imageSource_;
    /**
     * <pre>
     *图像来源
     * </pre>
     *
     * <code>string imageSource = 3;</code>
     * @return The imageSource.
     */
    public java.lang.String getImageSource() {
      java.lang.Object ref = imageSource_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imageSource_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *图像来源
     * </pre>
     *
     * <code>string imageSource = 3;</code>
     * @return The bytes for imageSource.
     */
    public com.google.protobuf.ByteString
        getImageSourceBytes() {
      java.lang.Object ref = imageSource_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TITLE_FIELD_NUMBER = 4;
    private volatile java.lang.Object title_;
    /**
     * <pre>
     *题名
     * </pre>
     *
     * <code>string title = 4;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *题名
     * </pre>
     *
     * <code>string title = 4;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGEDATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString imageData_;
    /**
     * <pre>
     *图片数据
     * </pre>
     *
     * <code>bytes imageData = 5;</code>
     * @return The imageData.
     */
    public com.google.protobuf.ByteString getImageData() {
      return imageData_;
    }

    public static final int FILEFORMAT_FIELD_NUMBER = 6;
    private volatile java.lang.Object fileFormat_;
    /**
     * <pre>
     *图像文件格式
     * </pre>
     *
     * <code>string fileFormat = 6;</code>
     * @return The fileFormat.
     */
    public java.lang.String getFileFormat() {
      java.lang.Object ref = fileFormat_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileFormat_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *图像文件格式
     * </pre>
     *
     * <code>string fileFormat = 6;</code>
     * @return The bytes for fileFormat.
     */
    public com.google.protobuf.ByteString
        getFileFormatBytes() {
      java.lang.Object ref = fileFormat_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileFormat_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SHOTPLACEFULLADRESS_FIELD_NUMBER = 7;
    private volatile java.lang.Object shotPlaceFullAdress_;
    /**
     * <pre>
     *拍摄地点区划内详细地址
     * </pre>
     *
     * <code>string shotPlaceFullAdress = 7;</code>
     * @return The shotPlaceFullAdress.
     */
    public java.lang.String getShotPlaceFullAdress() {
      java.lang.Object ref = shotPlaceFullAdress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shotPlaceFullAdress_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *拍摄地点区划内详细地址
     * </pre>
     *
     * <code>string shotPlaceFullAdress = 7;</code>
     * @return The bytes for shotPlaceFullAdress.
     */
    public com.google.protobuf.ByteString
        getShotPlaceFullAdressBytes() {
      java.lang.Object ref = shotPlaceFullAdress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shotPlaceFullAdress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SHOTTIME_FIELD_NUMBER = 8;
    private long shotTime_;
    /**
     * <pre>
     *拍摄时间
     * </pre>
     *
     * <code>int64 shotTime = 8;</code>
     * @return The shotTime.
     */
    public long getShotTime() {
      return shotTime_;
    }

    public static final int EVENTSORT_FIELD_NUMBER = 9;
    private int eventSort_;
    /**
     * <pre>
     *事件分类
     * </pre>
     *
     * <code>int32 eventSort = 9;</code>
     * @return The eventSort.
     */
    public int getEventSort() {
      return eventSort_;
    }

    public static final int IMAGETYPE_FIELD_NUMBER = 10;
    private int imageType_;
    /**
     * <pre>
     *图像类型
     * </pre>
     *
     * <code>int32 imageType = 10;</code>
     * @return The imageType.
     */
    public int getImageType() {
      return imageType_;
    }

    public static final int INFOKIND_FIELD_NUMBER = 11;
    private int infoKind_;
    /**
     * <pre>
     *信息分类
     * </pre>
     *
     * <code>int32 infoKind = 11;</code>
     * @return The infoKind.
     */
    public int getInfoKind() {
      return infoKind_;
    }

    public static final int STORAGEPATH_FIELD_NUMBER = 12;
    private volatile java.lang.Object storagePath_;
    /**
     * <pre>
     *存储路径
     * </pre>
     *
     * <code>string storagePath = 12;</code>
     * @return The storagePath.
     */
    public java.lang.String getStoragePath() {
      java.lang.Object ref = storagePath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        storagePath_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *存储路径
     * </pre>
     *
     * <code>string storagePath = 12;</code>
     * @return The bytes for storagePath.
     */
    public com.google.protobuf.ByteString
        getStoragePathBytes() {
      java.lang.Object ref = storagePath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        storagePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENTDESCRIPTION_FIELD_NUMBER = 13;
    private volatile java.lang.Object contentDescription_;
    /**
     * <pre>
     *内容描述
     * </pre>
     *
     * <code>string contentDescription = 13;</code>
     * @return The contentDescription.
     */
    public java.lang.String getContentDescription() {
      java.lang.Object ref = contentDescription_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contentDescription_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *内容描述
     * </pre>
     *
     * <code>string contentDescription = 13;</code>
     * @return The bytes for contentDescription.
     */
    public com.google.protobuf.ByteString
        getContentDescriptionBytes() {
      java.lang.Object ref = contentDescription_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contentDescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDeviceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceId_);
      }
      if (!getImageIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, imageId_);
      }
      if (!getImageSourceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, imageSource_);
      }
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, title_);
      }
      if (!imageData_.isEmpty()) {
        output.writeBytes(5, imageData_);
      }
      if (!getFileFormatBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, fileFormat_);
      }
      if (!getShotPlaceFullAdressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, shotPlaceFullAdress_);
      }
      if (shotTime_ != 0L) {
        output.writeInt64(8, shotTime_);
      }
      if (eventSort_ != 0) {
        output.writeInt32(9, eventSort_);
      }
      if (imageType_ != 0) {
        output.writeInt32(10, imageType_);
      }
      if (infoKind_ != 0) {
        output.writeInt32(11, infoKind_);
      }
      if (!getStoragePathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, storagePath_);
      }
      if (!getContentDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, contentDescription_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDeviceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceId_);
      }
      if (!getImageIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, imageId_);
      }
      if (!getImageSourceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, imageSource_);
      }
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, title_);
      }
      if (!imageData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, imageData_);
      }
      if (!getFileFormatBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, fileFormat_);
      }
      if (!getShotPlaceFullAdressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, shotPlaceFullAdress_);
      }
      if (shotTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, shotTime_);
      }
      if (eventSort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, eventSort_);
      }
      if (imageType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, imageType_);
      }
      if (infoKind_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, infoKind_);
      }
      if (!getStoragePathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, storagePath_);
      }
      if (!getContentDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, contentDescription_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo)) {
        return super.equals(obj);
      }
      com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo other = (com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo) obj;

      if (!getDeviceId()
          .equals(other.getDeviceId())) return false;
      if (!getImageId()
          .equals(other.getImageId())) return false;
      if (!getImageSource()
          .equals(other.getImageSource())) return false;
      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (!getImageData()
          .equals(other.getImageData())) return false;
      if (!getFileFormat()
          .equals(other.getFileFormat())) return false;
      if (!getShotPlaceFullAdress()
          .equals(other.getShotPlaceFullAdress())) return false;
      if (getShotTime()
          != other.getShotTime()) return false;
      if (getEventSort()
          != other.getEventSort()) return false;
      if (getImageType()
          != other.getImageType()) return false;
      if (getInfoKind()
          != other.getInfoKind()) return false;
      if (!getStoragePath()
          .equals(other.getStoragePath())) return false;
      if (!getContentDescription()
          .equals(other.getContentDescription())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceId().hashCode();
      hash = (37 * hash) + IMAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getImageId().hashCode();
      hash = (37 * hash) + IMAGESOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getImageSource().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + IMAGEDATA_FIELD_NUMBER;
      hash = (53 * hash) + getImageData().hashCode();
      hash = (37 * hash) + FILEFORMAT_FIELD_NUMBER;
      hash = (53 * hash) + getFileFormat().hashCode();
      hash = (37 * hash) + SHOTPLACEFULLADRESS_FIELD_NUMBER;
      hash = (53 * hash) + getShotPlaceFullAdress().hashCode();
      hash = (37 * hash) + SHOTTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getShotTime());
      hash = (37 * hash) + EVENTSORT_FIELD_NUMBER;
      hash = (53 * hash) + getEventSort();
      hash = (37 * hash) + IMAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getImageType();
      hash = (37 * hash) + INFOKIND_FIELD_NUMBER;
      hash = (53 * hash) + getInfoKind();
      hash = (37 * hash) + STORAGEPATH_FIELD_NUMBER;
      hash = (53 * hash) + getStoragePath().hashCode();
      hash = (37 * hash) + CONTENTDESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getContentDescription().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.dtc.analytic.online.protobuf.SubImageInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.dtc.analytic.online.protobuf.SubImageInfo)
        com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dtc.analytic.online.protobuf.SubImageInfoObjProto.internal_static_com_dtc_analytic_online_protobuf_SubImageInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dtc.analytic.online.protobuf.SubImageInfoObjProto.internal_static_com_dtc_analytic_online_protobuf_SubImageInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo.class, com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo.Builder.class);
      }

      // Construct using com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        deviceId_ = "";

        imageId_ = "";

        imageSource_ = "";

        title_ = "";

        imageData_ = com.google.protobuf.ByteString.EMPTY;

        fileFormat_ = "";

        shotPlaceFullAdress_ = "";

        shotTime_ = 0L;

        eventSort_ = 0;

        imageType_ = 0;

        infoKind_ = 0;

        storagePath_ = "";

        contentDescription_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dtc.analytic.online.protobuf.SubImageInfoObjProto.internal_static_com_dtc_analytic_online_protobuf_SubImageInfo_descriptor;
      }

      @java.lang.Override
      public com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo getDefaultInstanceForType() {
        return com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo build() {
        com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo buildPartial() {
        com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo result = new com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo(this);
        result.deviceId_ = deviceId_;
        result.imageId_ = imageId_;
        result.imageSource_ = imageSource_;
        result.title_ = title_;
        result.imageData_ = imageData_;
        result.fileFormat_ = fileFormat_;
        result.shotPlaceFullAdress_ = shotPlaceFullAdress_;
        result.shotTime_ = shotTime_;
        result.eventSort_ = eventSort_;
        result.imageType_ = imageType_;
        result.infoKind_ = infoKind_;
        result.storagePath_ = storagePath_;
        result.contentDescription_ = contentDescription_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo) {
          return mergeFrom((com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo other) {
        if (other == com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo.getDefaultInstance()) return this;
        if (!other.getDeviceId().isEmpty()) {
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (!other.getImageId().isEmpty()) {
          imageId_ = other.imageId_;
          onChanged();
        }
        if (!other.getImageSource().isEmpty()) {
          imageSource_ = other.imageSource_;
          onChanged();
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (other.getImageData() != com.google.protobuf.ByteString.EMPTY) {
          setImageData(other.getImageData());
        }
        if (!other.getFileFormat().isEmpty()) {
          fileFormat_ = other.fileFormat_;
          onChanged();
        }
        if (!other.getShotPlaceFullAdress().isEmpty()) {
          shotPlaceFullAdress_ = other.shotPlaceFullAdress_;
          onChanged();
        }
        if (other.getShotTime() != 0L) {
          setShotTime(other.getShotTime());
        }
        if (other.getEventSort() != 0) {
          setEventSort(other.getEventSort());
        }
        if (other.getImageType() != 0) {
          setImageType(other.getImageType());
        }
        if (other.getInfoKind() != 0) {
          setInfoKind(other.getInfoKind());
        }
        if (!other.getStoragePath().isEmpty()) {
          storagePath_ = other.storagePath_;
          onChanged();
        }
        if (!other.getContentDescription().isEmpty()) {
          contentDescription_ = other.contentDescription_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object deviceId_ = "";
      /**
       * <pre>
       *设备编码
       * </pre>
       *
       * <code>string deviceId = 1;</code>
       * @return The deviceId.
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *设备编码
       * </pre>
       *
       * <code>string deviceId = 1;</code>
       * @return The bytes for deviceId.
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *设备编码
       * </pre>
       *
       * <code>string deviceId = 1;</code>
       * @param value The deviceId to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *设备编码
       * </pre>
       *
       * <code>string deviceId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceId() {
        
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *设备编码
       * </pre>
       *
       * <code>string deviceId = 1;</code>
       * @param value The bytes for deviceId to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object imageId_ = "";
      /**
       * <pre>
       *图像标识
       * </pre>
       *
       * <code>string imageId = 2;</code>
       * @return The imageId.
       */
      public java.lang.String getImageId() {
        java.lang.Object ref = imageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          imageId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *图像标识
       * </pre>
       *
       * <code>string imageId = 2;</code>
       * @return The bytes for imageId.
       */
      public com.google.protobuf.ByteString
          getImageIdBytes() {
        java.lang.Object ref = imageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *图像标识
       * </pre>
       *
       * <code>string imageId = 2;</code>
       * @param value The imageId to set.
       * @return This builder for chaining.
       */
      public Builder setImageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *图像标识
       * </pre>
       *
       * <code>string imageId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearImageId() {
        
        imageId_ = getDefaultInstance().getImageId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *图像标识
       * </pre>
       *
       * <code>string imageId = 2;</code>
       * @param value The bytes for imageId to set.
       * @return This builder for chaining.
       */
      public Builder setImageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        imageId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object imageSource_ = "";
      /**
       * <pre>
       *图像来源
       * </pre>
       *
       * <code>string imageSource = 3;</code>
       * @return The imageSource.
       */
      public java.lang.String getImageSource() {
        java.lang.Object ref = imageSource_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          imageSource_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *图像来源
       * </pre>
       *
       * <code>string imageSource = 3;</code>
       * @return The bytes for imageSource.
       */
      public com.google.protobuf.ByteString
          getImageSourceBytes() {
        java.lang.Object ref = imageSource_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imageSource_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *图像来源
       * </pre>
       *
       * <code>string imageSource = 3;</code>
       * @param value The imageSource to set.
       * @return This builder for chaining.
       */
      public Builder setImageSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imageSource_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *图像来源
       * </pre>
       *
       * <code>string imageSource = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearImageSource() {
        
        imageSource_ = getDefaultInstance().getImageSource();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *图像来源
       * </pre>
       *
       * <code>string imageSource = 3;</code>
       * @param value The bytes for imageSource to set.
       * @return This builder for chaining.
       */
      public Builder setImageSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        imageSource_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <pre>
       *题名
       * </pre>
       *
       * <code>string title = 4;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *题名
       * </pre>
       *
       * <code>string title = 4;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *题名
       * </pre>
       *
       * <code>string title = 4;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *题名
       * </pre>
       *
       * <code>string title = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *题名
       * </pre>
       *
       * <code>string title = 4;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString imageData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *图片数据
       * </pre>
       *
       * <code>bytes imageData = 5;</code>
       * @return The imageData.
       */
      public com.google.protobuf.ByteString getImageData() {
        return imageData_;
      }
      /**
       * <pre>
       *图片数据
       * </pre>
       *
       * <code>bytes imageData = 5;</code>
       * @param value The imageData to set.
       * @return This builder for chaining.
       */
      public Builder setImageData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imageData_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *图片数据
       * </pre>
       *
       * <code>bytes imageData = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearImageData() {
        
        imageData_ = getDefaultInstance().getImageData();
        onChanged();
        return this;
      }

      private java.lang.Object fileFormat_ = "";
      /**
       * <pre>
       *图像文件格式
       * </pre>
       *
       * <code>string fileFormat = 6;</code>
       * @return The fileFormat.
       */
      public java.lang.String getFileFormat() {
        java.lang.Object ref = fileFormat_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileFormat_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *图像文件格式
       * </pre>
       *
       * <code>string fileFormat = 6;</code>
       * @return The bytes for fileFormat.
       */
      public com.google.protobuf.ByteString
          getFileFormatBytes() {
        java.lang.Object ref = fileFormat_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileFormat_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *图像文件格式
       * </pre>
       *
       * <code>string fileFormat = 6;</code>
       * @param value The fileFormat to set.
       * @return This builder for chaining.
       */
      public Builder setFileFormat(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileFormat_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *图像文件格式
       * </pre>
       *
       * <code>string fileFormat = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileFormat() {
        
        fileFormat_ = getDefaultInstance().getFileFormat();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *图像文件格式
       * </pre>
       *
       * <code>string fileFormat = 6;</code>
       * @param value The bytes for fileFormat to set.
       * @return This builder for chaining.
       */
      public Builder setFileFormatBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileFormat_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object shotPlaceFullAdress_ = "";
      /**
       * <pre>
       *拍摄地点区划内详细地址
       * </pre>
       *
       * <code>string shotPlaceFullAdress = 7;</code>
       * @return The shotPlaceFullAdress.
       */
      public java.lang.String getShotPlaceFullAdress() {
        java.lang.Object ref = shotPlaceFullAdress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          shotPlaceFullAdress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *拍摄地点区划内详细地址
       * </pre>
       *
       * <code>string shotPlaceFullAdress = 7;</code>
       * @return The bytes for shotPlaceFullAdress.
       */
      public com.google.protobuf.ByteString
          getShotPlaceFullAdressBytes() {
        java.lang.Object ref = shotPlaceFullAdress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          shotPlaceFullAdress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *拍摄地点区划内详细地址
       * </pre>
       *
       * <code>string shotPlaceFullAdress = 7;</code>
       * @param value The shotPlaceFullAdress to set.
       * @return This builder for chaining.
       */
      public Builder setShotPlaceFullAdress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        shotPlaceFullAdress_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *拍摄地点区划内详细地址
       * </pre>
       *
       * <code>string shotPlaceFullAdress = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearShotPlaceFullAdress() {
        
        shotPlaceFullAdress_ = getDefaultInstance().getShotPlaceFullAdress();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *拍摄地点区划内详细地址
       * </pre>
       *
       * <code>string shotPlaceFullAdress = 7;</code>
       * @param value The bytes for shotPlaceFullAdress to set.
       * @return This builder for chaining.
       */
      public Builder setShotPlaceFullAdressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        shotPlaceFullAdress_ = value;
        onChanged();
        return this;
      }

      private long shotTime_ ;
      /**
       * <pre>
       *拍摄时间
       * </pre>
       *
       * <code>int64 shotTime = 8;</code>
       * @return The shotTime.
       */
      public long getShotTime() {
        return shotTime_;
      }
      /**
       * <pre>
       *拍摄时间
       * </pre>
       *
       * <code>int64 shotTime = 8;</code>
       * @param value The shotTime to set.
       * @return This builder for chaining.
       */
      public Builder setShotTime(long value) {
        
        shotTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *拍摄时间
       * </pre>
       *
       * <code>int64 shotTime = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearShotTime() {
        
        shotTime_ = 0L;
        onChanged();
        return this;
      }

      private int eventSort_ ;
      /**
       * <pre>
       *事件分类
       * </pre>
       *
       * <code>int32 eventSort = 9;</code>
       * @return The eventSort.
       */
      public int getEventSort() {
        return eventSort_;
      }
      /**
       * <pre>
       *事件分类
       * </pre>
       *
       * <code>int32 eventSort = 9;</code>
       * @param value The eventSort to set.
       * @return This builder for chaining.
       */
      public Builder setEventSort(int value) {
        
        eventSort_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *事件分类
       * </pre>
       *
       * <code>int32 eventSort = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearEventSort() {
        
        eventSort_ = 0;
        onChanged();
        return this;
      }

      private int imageType_ ;
      /**
       * <pre>
       *图像类型
       * </pre>
       *
       * <code>int32 imageType = 10;</code>
       * @return The imageType.
       */
      public int getImageType() {
        return imageType_;
      }
      /**
       * <pre>
       *图像类型
       * </pre>
       *
       * <code>int32 imageType = 10;</code>
       * @param value The imageType to set.
       * @return This builder for chaining.
       */
      public Builder setImageType(int value) {
        
        imageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *图像类型
       * </pre>
       *
       * <code>int32 imageType = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearImageType() {
        
        imageType_ = 0;
        onChanged();
        return this;
      }

      private int infoKind_ ;
      /**
       * <pre>
       *信息分类
       * </pre>
       *
       * <code>int32 infoKind = 11;</code>
       * @return The infoKind.
       */
      public int getInfoKind() {
        return infoKind_;
      }
      /**
       * <pre>
       *信息分类
       * </pre>
       *
       * <code>int32 infoKind = 11;</code>
       * @param value The infoKind to set.
       * @return This builder for chaining.
       */
      public Builder setInfoKind(int value) {
        
        infoKind_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *信息分类
       * </pre>
       *
       * <code>int32 infoKind = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearInfoKind() {
        
        infoKind_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object storagePath_ = "";
      /**
       * <pre>
       *存储路径
       * </pre>
       *
       * <code>string storagePath = 12;</code>
       * @return The storagePath.
       */
      public java.lang.String getStoragePath() {
        java.lang.Object ref = storagePath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          storagePath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *存储路径
       * </pre>
       *
       * <code>string storagePath = 12;</code>
       * @return The bytes for storagePath.
       */
      public com.google.protobuf.ByteString
          getStoragePathBytes() {
        java.lang.Object ref = storagePath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          storagePath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *存储路径
       * </pre>
       *
       * <code>string storagePath = 12;</code>
       * @param value The storagePath to set.
       * @return This builder for chaining.
       */
      public Builder setStoragePath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        storagePath_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *存储路径
       * </pre>
       *
       * <code>string storagePath = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearStoragePath() {
        
        storagePath_ = getDefaultInstance().getStoragePath();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *存储路径
       * </pre>
       *
       * <code>string storagePath = 12;</code>
       * @param value The bytes for storagePath to set.
       * @return This builder for chaining.
       */
      public Builder setStoragePathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        storagePath_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object contentDescription_ = "";
      /**
       * <pre>
       *内容描述
       * </pre>
       *
       * <code>string contentDescription = 13;</code>
       * @return The contentDescription.
       */
      public java.lang.String getContentDescription() {
        java.lang.Object ref = contentDescription_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contentDescription_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *内容描述
       * </pre>
       *
       * <code>string contentDescription = 13;</code>
       * @return The bytes for contentDescription.
       */
      public com.google.protobuf.ByteString
          getContentDescriptionBytes() {
        java.lang.Object ref = contentDescription_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contentDescription_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *内容描述
       * </pre>
       *
       * <code>string contentDescription = 13;</code>
       * @param value The contentDescription to set.
       * @return This builder for chaining.
       */
      public Builder setContentDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        contentDescription_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *内容描述
       * </pre>
       *
       * <code>string contentDescription = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearContentDescription() {
        
        contentDescription_ = getDefaultInstance().getContentDescription();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *内容描述
       * </pre>
       *
       * <code>string contentDescription = 13;</code>
       * @param value The bytes for contentDescription to set.
       * @return This builder for chaining.
       */
      public Builder setContentDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        contentDescription_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.dtc.analytic.online.protobuf.SubImageInfo)
    }

    // @@protoc_insertion_point(class_scope:com.dtc.analytic.online.protobuf.SubImageInfo)
    private static final com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo();
    }

    public static com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SubImageInfo>
        PARSER = new com.google.protobuf.AbstractParser<SubImageInfo>() {
      @java.lang.Override
      public SubImageInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SubImageInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SubImageInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SubImageInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dtc.analytic.online.protobuf.SubImageInfoObjProto.SubImageInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dtc_analytic_online_protobuf_SubImageInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dtc_analytic_online_protobuf_SubImageInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025SubImageInfoObj.proto\022 com.dtc.analyti" +
      "c.online.protobuf\"\224\002\n\014SubImageInfo\022\020\n\010de" +
      "viceId\030\001 \001(\t\022\017\n\007imageId\030\002 \001(\t\022\023\n\013imageSo" +
      "urce\030\003 \001(\t\022\r\n\005title\030\004 \001(\t\022\021\n\timageData\030\005" +
      " \001(\014\022\022\n\nfileFormat\030\006 \001(\t\022\033\n\023shotPlaceFul" +
      "lAdress\030\007 \001(\t\022\020\n\010shotTime\030\010 \001(\003\022\021\n\tevent" +
      "Sort\030\t \001(\005\022\021\n\timageType\030\n \001(\005\022\020\n\010infoKin" +
      "d\030\013 \001(\005\022\023\n\013storagePath\030\014 \001(\t\022\032\n\022contentD" +
      "escription\030\r \001(\tB\026B\024SubImageInfoObjProto" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_dtc_analytic_online_protobuf_SubImageInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_dtc_analytic_online_protobuf_SubImageInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dtc_analytic_online_protobuf_SubImageInfo_descriptor,
        new java.lang.String[] { "DeviceId", "ImageId", "ImageSource", "Title", "ImageData", "FileFormat", "ShotPlaceFullAdress", "ShotTime", "EventSort", "ImageType", "InfoKind", "StoragePath", "ContentDescription", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
